package br.stylus.funilaria.view.telasPesquisas;

import br.stylus.funilaria.controller.gestao.pessoa.contato.Contato;
import br.stylus.funilaria.controller.gestao.pessoa.fisica.Funcionario;
import br.stylus.funilaria.controller.utilitarios.formatacoes.ModeloTabela;
import br.stylus.funilaria.model.persistencia.pesquisas.PesquisaFuncionarioDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class FormPesquisarFuncionario extends javax.swing.JFrame {
    
    Funcionario funcionario = new Funcionario();
    Contato contato = new Contato();
    PesquisaFuncionarioDao pesqFuncionario = new PesquisaFuncionarioDao();
    
    public FormPesquisarFuncionario() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloPesquisaFun = new javax.swing.JLabel();
        jLabelTipoPesquisaFun = new javax.swing.JLabel();
        jComboBoxTipoPesquisa = new javax.swing.JComboBox<>();
        jTextFieldPesuisaFun = new javax.swing.JTextField();
        jButtonPesquisarFun = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaFun = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Funcionário");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloPesquisaFun.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabelTituloPesquisaFun.setText("Pesquisar Funcionário");

        jLabelTipoPesquisaFun.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabelTipoPesquisaFun.setText("Pesquisar por :");

        jComboBoxTipoPesquisa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jComboBoxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Nome", "Cargo", "Cpf" }));
        jComboBoxTipoPesquisa.setToolTipText("");

        jButtonPesquisarFun.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jButtonPesquisarFun.setText("Pesquisar");
        jButtonPesquisarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFunActionPerformed(evt);
            }
        });

        jTablePesquisaFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisaFun);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTipoPesquisaFun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesuisaFun)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloPesquisaFun)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPesquisaFun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesuisaFun, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoPesquisaFun)
                        .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisarFun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 30, 800, 360);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/stylus/funilaria/view/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-10, -20, 910, 450);

        setSize(new java.awt.Dimension(894, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFunActionPerformed
        funcionario.setPesquisaFun(jTextFieldPesuisaFun.getText());
         funcionario.setContato(contato);
        if(jComboBoxTipoPesquisa.getSelectedItem().equals("Nome")){         
            pesqFuncionario.pesquisaNome(funcionario);
            preencherTabela();
       } else if(jComboBoxTipoPesquisa.getSelectedItem().equals("Cargo")){
           pesqFuncionario.pesquisaCargo(funcionario);
           preencherTabela();
       } else if(jComboBoxTipoPesquisa.getSelectedItem().equals("Cpf")) {
           pesqFuncionario.pesquisaCpf(funcionario);
            preencherTabela();
       } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Selecione...")){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma opção para a pesquisa!");
        }
    }//GEN-LAST:event_jButtonPesquisarFunActionPerformed

  private void preencherTabela() {
      
       ArrayList dados = new ArrayList();
       String colunas[] = new String [] {"ID","Nome","Cpf","Sexo","Cargo","Endereco","Celular","Email"};
  // do{
       dados.add(new Object[] {funcionario.getCodFuncionario(),funcionario.getNome(),funcionario.getCpf(),funcionario.getSexo(),funcionario.getCargo(),contato.getEndereco(),contato.getCelular(),contato.getEmail()});
   // while();   
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        jTablePesquisaFun.setModel(modelo);
        jTablePesquisaFun.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisaFun.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTablePesquisaFun.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablePesquisaFun.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTablePesquisaFun.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTablePesquisaFun.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTablePesquisaFun.getColumnModel().getColumn(5).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(6).setPreferredWidth(110);
        jTablePesquisaFun.getColumnModel().getColumn(6).setResizable(false);
        jTablePesquisaFun.getColumnModel().getColumn(7).setPreferredWidth(110);
        jTablePesquisaFun.getColumnModel().getColumn(7).setResizable(false);
        jTablePesquisaFun.getTableHeader().setReorderingAllowed(false);
        jTablePesquisaFun.setAutoResizeMode(jTablePesquisaFun.AUTO_RESIZE_OFF);
        jTablePesquisaFun.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  }
          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisarFun;
    private javax.swing.JComboBox<String> jComboBoxTipoPesquisa;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTipoPesquisaFun;
    private javax.swing.JLabel jLabelTituloPesquisaFun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaFun;
    private javax.swing.JTextField jTextFieldPesuisaFun;
    // End of variables declaration//GEN-END:variables
}
