package br.stylus.funilaria.view.telasPesquisas;

import br.stylus.funilaria.controller.gestao.pessoa.contato.Contato;
import br.stylus.funilaria.controller.gestao.pessoa.juridica.ClientePessoaJuridica;
import br.stylus.funilaria.controller.utilitarios.formatacoes.ModeloTabela;
import br.stylus.funilaria.model.persistencia.pesquisas.PesquisaClientePjDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class FormPesquisarClientePessoaJ extends javax.swing.JFrame {
    
    ClientePessoaJuridica clientePj = new ClientePessoaJuridica();
    Contato contato = new Contato();
    PesquisaClientePjDao pesqFuncionario = new PesquisaClientePjDao();
    
    public FormPesquisarClientePessoaJ() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloPesquisaFun = new javax.swing.JLabel();
        jLabelTipoPesquisaCliente = new javax.swing.JLabel();
        jTextFieldPesuisaCliente = new javax.swing.JTextField();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaCliente = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Cliente Pessoa Jurídica");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloPesquisaFun.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabelTituloPesquisaFun.setText("Pesquisar Cliente");

        jLabelTipoPesquisaCliente.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabelTipoPesquisaCliente.setText("Digite o nome Fantasia :");

        jButtonPesquisarCliente.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jButtonPesquisarCliente.setText("Pesquisar");
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        jTablePesquisaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisaCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTipoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesuisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabelTituloPesquisaFun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelTituloPesquisaFun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesuisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipoPesquisaCliente))
                    .addComponent(jButtonPesquisarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 30, 800, 360);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/stylus/funilaria/view/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-10, -20, 910, 450);

        setSize(new java.awt.Dimension(894, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        clientePj.setPesquisaClientePj(jTextFieldPesuisaCliente.getText());
         clientePj.setContato(contato);
        if(jTextFieldPesuisaCliente.getText().isEmpty()){         
           JOptionPane.showMessageDialog(rootPane, "Preencha o campo para fazer a pesquisa!");
           jTextFieldPesuisaCliente.requestFocus();
           
       } else {
          pesqFuncionario.pesquisaCLientePj(clientePj);
          preencherTabela();
        }
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

  private void preencherTabela() {
      
       ArrayList dados = new ArrayList();
       String colunas[] = new String [] {"ID","Nome Fantasia","Razão Social","CNPJ","Endereco","Telefone","Email"};
  // do{
       dados.add(new Object[] {clientePj.getCodClienteJ(),clientePj.getNomeFantasia(),clientePj.getRazaoSocial(),clientePj.getCnpj(),contato.getEndereco(),contato.getCelular(),contato.getEmail()});
   // while();   
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        jTablePesquisaCliente.setModel(modelo);
        jTablePesquisaCliente.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisaCliente.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTablePesquisaCliente.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablePesquisaCliente.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTablePesquisaCliente.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTablePesquisaCliente.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTablePesquisaCliente.getColumnModel().getColumn(5).setResizable(false);
        jTablePesquisaCliente.getColumnModel().getColumn(6).setPreferredWidth(170);
        jTablePesquisaCliente.getColumnModel().getColumn(6).setResizable(false);
        jTablePesquisaCliente.getTableHeader().setReorderingAllowed(false);
        jTablePesquisaCliente.setAutoResizeMode(jTablePesquisaCliente.AUTO_RESIZE_OFF);
        jTablePesquisaCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  }
          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarClientePessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarClientePessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarClientePessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarClientePessoaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisarClientePessoaJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTipoPesquisaCliente;
    private javax.swing.JLabel jLabelTituloPesquisaFun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaCliente;
    private javax.swing.JTextField jTextFieldPesuisaCliente;
    // End of variables declaration//GEN-END:variables
}
