package br.stylus.funilaria.view.telasPesquisas;

import br.stylus.funilaria.controller.gestao.negocios.Produtos;
import br.stylus.funilaria.controller.utilitarios.formatacoes.ModeloTabela;
import br.stylus.funilaria.model.persistencia.pesquisas.PesquisaProdutoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class FormPesquisarProduto extends javax.swing.JFrame {
    
    Produtos produtos = new Produtos();
    PesquisaProdutoDao pesqProduto = new PesquisaProdutoDao();
    
    public FormPesquisarProduto() {
        initComponents();
      //  preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloPesquisa = new javax.swing.JLabel();
        jLabelTipoPesquisa = new javax.swing.JLabel();
        jComboBoxTipoPesquisa = new javax.swing.JComboBox<>();
        jTextFieldPesuisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaProduto = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloPesquisa.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabelTituloPesquisa.setText("Pesquisar Produtos");

        jLabelTipoPesquisa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabelTipoPesquisa.setText("Pesquisar por :");

        jComboBoxTipoPesquisa.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jComboBoxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Marca", "Tipo", "Descrição" }));
        jComboBoxTipoPesquisa.setToolTipText("");

        jButtonPesquisar.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTablePesquisaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePesquisaProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTituloPesquisa)
                .addGap(237, 237, 237))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTipoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesuisa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesuisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoPesquisa)
                        .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 30, 640, 360);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/stylus/funilaria/view/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-10, -20, 780, 450);

        setSize(new java.awt.Dimension(735, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        produtos.setPesquisaproduto(jTextFieldPesuisa.getText());
         
        if(jComboBoxTipoPesquisa.getSelectedItem().equals("Marca")){         
            pesqProduto.pesquisarMarca(produtos);
            preencherTabela();
       } else if(jComboBoxTipoPesquisa.getSelectedItem().equals("Tipo")){
           pesqProduto.pesquisarTipo(produtos);
           preencherTabela();
       } else if(jComboBoxTipoPesquisa.getSelectedItem().equals("Descrição")) {
           pesqProduto.pesquisarDescricao(produtos);
            preencherTabela();
       } else if (jComboBoxTipoPesquisa.getSelectedItem().equals("Selecione...")){
       JOptionPane.showMessageDialog(rootPane, "Selecione uma opção para a pesquisa!");
       }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

  public void preencherTabela() {
      
       ArrayList dados = new ArrayList();
       String colunas[] = new String [] {"ID","Marca","Tipo","Descrição","Preço","Quatidade"};
     //  do {          
         dados.add(new Object[] {produtos.getCodProduto(),produtos.getMarca(),produtos.getTipo(),produtos.getDescricao(),produtos.getPreco(),produtos.getQuantidade()}); 
    //  } while (rootPaneCheckingEnabled);
       
      
        ModeloTabela modelo = new ModeloTabela(dados,colunas);
        jTablePesquisaProduto.setModel(modelo);
        jTablePesquisaProduto.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisaProduto.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisaProduto.getColumnModel().getColumn(1).setPreferredWidth(110);
        jTablePesquisaProduto.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisaProduto.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTablePesquisaProduto.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisaProduto.getColumnModel().getColumn(3).setPreferredWidth(122);
        jTablePesquisaProduto.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisaProduto.getColumnModel().getColumn(4).setPreferredWidth(115);
        jTablePesquisaProduto.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisaProduto.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTablePesquisaProduto.getColumnModel().getColumn(5).setResizable(false);
        jTablePesquisaProduto.getTableHeader().setReorderingAllowed(false);
        jTablePesquisaProduto.setAutoResizeMode(jTablePesquisaProduto.AUTO_RESIZE_OFF);
        jTablePesquisaProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
  }
          
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxTipoPesquisa;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTipoPesquisa;
    private javax.swing.JLabel jLabelTituloPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaProduto;
    private javax.swing.JTextField jTextFieldPesuisa;
    // End of variables declaration//GEN-END:variables
}
