package br.stylus.funilaria.view.telasIniciais;

import br.stylus.funilaria.view.telasCadastros.FormAdministrador;
import javax.swing.JOptionPane;

public class TelaBemVindo extends javax.swing.JFrame {

  
    public TelaBemVindo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTexto1 = new javax.swing.JLabel();
        jLabelTexto2 = new javax.swing.JLabel();
        jLabelNomeEmpresa = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jLabelFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seja Bem Vindo!");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTexto1.setText("Seja bem vindo ao Stylus, este software irá auxlia-lo no gerenciamento de sua funilaria e pintura.");
        getContentPane().add(jLabelTexto1);
        jLabelTexto1.setBounds(29, 160, 530, 14);

        jLabelTexto2.setText("Esperamos que você aproveite ao máximo e nos envie seus comentários!");
        getContentPane().add(jLabelTexto2);
        jLabelTexto2.setBounds(99, 183, 430, 14);

        jLabelNomeEmpresa.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabelNomeEmpresa.setText("Stylus Funilaria e Pintura");
        getContentPane().add(jLabelNomeEmpresa);
        jLabelNomeEmpresa.setBounds(183, 116, 270, 24);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/stylus/funilaria/view/imagens/LogoLogin.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(219, 35, 125, 75);

        jButtonEntrar.setFont(new java.awt.Font("Century Schoolbook L", 0, 18)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(235, 243, 105, 43);

        jLabelFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/stylus/funilaria/view/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoTela);
        jLabelFundoTela.setBounds(-11, -7, 650, 360);

        setSize(new java.awt.Dimension(618, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        FormAdministrador tela = new FormAdministrador();
        tela.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(rootPane, "Agora se cadastre no sistema!");
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBemVindo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelFundoTela;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNomeEmpresa;
    private javax.swing.JLabel jLabelTexto1;
    private javax.swing.JLabel jLabelTexto2;
    // End of variables declaration//GEN-END:variables
}
